namespace MainMenu
{
    partial class UserKeys
    {
        private System.Windows.Forms.PictureBox pictureBox1;
        private System.Windows.Forms.Label ProductShortcut_1;
        private System.Windows.Forms.Label ProductShortcut_2;
        private System.Windows.Forms.Label ProductShortcut_3;
        private BaseDeDatosDataSet baseDeDatosDataSet;
        private BaseDeDatosDataSetTableAdapters.ProductosTableAdapter productosTableAdapter;
        private BaseDeDatosDataSetTableAdapters.Prod_detalleTableAdapter prod_detalleTableAdapter1;
        private System.Windows.Forms.ListView listView1;
        private System.Windows.Forms.Label ProductShortcut_4;
        private System.Windows.Forms.Label ProductShortcut_5;
        private System.Windows.Forms.Label ProductShortcut_6;
        private System.Windows.Forms.Label ProductShortcut_7;
        private System.Windows.Forms.Label ProductShortcut_8;
        private System.Windows.Forms.Label ProductShortcut_9;
        private System.Windows.Forms.Label ProductShortcut_10;
        private System.Windows.Forms.Label ProductShortcut_11;
        private System.Windows.Forms.Label ProductShortcut_12;
        private System.Windows.Forms.Label ProductShortcut_13;
        private System.Windows.Forms.Label ProductShortcut_14;
        private System.Windows.Forms.Label ProductShortcut_15;
        private System.Windows.Forms.Label ProductShortcut_16;
        private System.Windows.Forms.Label ProductShortcut_17;
        private System.Windows.Forms.Label ProductShortcut_18;
        private System.Windows.Forms.Label ProductShortcut_19;
        private System.Windows.Forms.Label ProductShortcut_20;
        private System.Windows.Forms.Label ProductShortcut_21;
        private System.Windows.Forms.Label ProductShortcut_22;
        private System.Windows.Forms.Label ProductShortcut_23;
        private System.Windows.Forms.Label ProductShortcut_24;
        private System.Windows.Forms.Label ProductShortcut_25;
        private System.Windows.Forms.Label ProductShortcut_26;
        private System.Windows.Forms.Label ProductShortcut_27;
        private System.Windows.Forms.Label ProductShortcut_28;
        private System.Windows.Forms.Label ProductShortcut_29;
        private System.Windows.Forms.Label ProductShortcut_30;
        private System.Windows.Forms.Label ProductShortcut_31;
        private System.Windows.Forms.Label ProductShortcut_32;
        private System.Windows.Forms.Label ProductShortcut_33;
        private System.Windows.Forms.Label ProductShortcut_34;
        private System.Windows.Forms.Label ProductShortcut_35;
        private System.Windows.Forms.Button btn_ClearAll;
        public System.Windows.Forms.ToolStrip toolStrip31;
        private System.Windows.Forms.ToolStripLabel toolStripLabel1;
        private System.Windows.Forms.ToolStripLabel toolStripLabel2;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator1;
        private System.Windows.Forms.ToolStripLabel toolStripLabel3;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator3;
        private System.Windows.Forms.ToolStripButton StripCerrar;
        private System.Windows.Forms.ToolStripButton StripEnviar;
        private System.Windows.Forms.ImageList imageList2;
        private System.Windows.Forms.ToolStripButton StripGuardar;
        private System.Windows.Forms.Label lbl_indicator_visual_1;
        private System.Windows.Forms.Label lbl_indicator_visual_2;
        private System.Windows.Forms.Label lbl_indicator_1;
        private System.Windows.Forms.Label lbl_indicator_2;
    }
}